// apps/blinksocial-web/src/app/pages/new-workspace/steps/step-workspace-basics/step-workspace-basics.component.ts
import { Component, inject } from '@angular/core';
import { NewWorkspaceFormService } from '../../new-workspace-form.service';
import { TooltipComponent } from '../../../../shared/tooltip/tooltip.component';

@Component({
  selector: 'app-step-workspace-basics',
  imports: [TooltipComponent],
  templateUrl: './step-workspace-basics.component.html',
  styleUrl: './step-workspace-basics.component.scss',
})
export class StepWorkspaceBasicsComponent {
  protected readonly formService = inject(NewWorkspaceFormService);
}

<div class="step-workspace-basics">
  <div class="step-header">
    <h2>Strategic Foundation</h2>
    <p class="step-subtitle">Define the purpose and mission your content strategy will serve.</p>
  </div>

  <div class="fields">
    <!-- Workspace Name -->
    <div class="field-group">
      <label class="field-label" for="workspace-name">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4.5 16.5c-1.5 1.26-2 5-2 5s3.74-.5 5-2c.71-.84.7-2.13-.09-2.91a2.18 2.18 0 0 0-2.91-.09z"/><path d="m12 15-3-3a22 22 0 0 1 2-3.95A12.88 12.88 0 0 1 22 2c0 2.72-.78 7.5-6 11a22.35 22.35 0 0 1-4 2z"/><path d="M9 12H4s.55-3.03 2-4c1.62-1.08 5 0 5 0"/><path d="M12 15v5s3.03-.55 4-2c1.08-1.62 0-5 0-5"/></svg>
        Workspace Name
        <app-tooltip text="The public name for your workspace as it appears in the dashboard and reports." />
      </label>
      <input id="workspace-name" type="text" class="field-input" placeholder="e.g. Hive Collective Main" [value]="formService.workspaceName()" (input)="formService.workspaceName.set($any($event.target).value)" />
    </div>

    <!-- Workspace Purpose -->
    <div class="field-group">
      <label class="field-label" for="workspace-purpose">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><circle cx="12" cy="12" r="6"/><circle cx="12" cy="12" r="2"/></svg>
        Workspace Purpose
        <app-tooltip text="Why this workspace exists and the primary goal it serves." />
      </label>
      <textarea id="workspace-purpose" class="field-textarea" placeholder="What is the primary reason this workspace exists?" [value]="formService.purpose()" (input)="formService.purpose.set($any($event.target).value)"></textarea>
    </div>

    <!-- Mission -->
    <div class="field-group">
      <label class="field-label" for="mission">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z"/></svg>
        Mission
        <app-tooltip text="Your long-term objective and the impact you want to achieve." />
      </label>
      <textarea id="mission" class="field-textarea" placeholder="What do you aim to achieve in the long term?" [value]="formService.mission()" (input)="formService.mission.set($any($event.target).value)"></textarea>
    </div>

  </div>
</div>

// figma/src/app/components/steps/StepWorkspaceBasics.tsx
import React from "react";
import { Input } from "@/app/components/ui/input";
import { Label } from "@/app/components/ui/label";
import { Textarea } from "@/app/components/ui/textarea";
import { Rocket, Target, Shield } from "lucide-react";
import { motion } from "motion/react";
import { cn } from "@/lib/utils";
import { FieldInfo } from "@/app/components/FieldInfo";

const fieldStyles = "bg-[#f3f4f6] border-none shadow-none focus-visible:ring-1 focus-visible:ring-gray-200 focus-visible:bg-[#edeff2] transition-colors";

export function StepWorkspaceBasics() {
  return (
    <motion.div
      initial={{ opacity: 0, x: 20 }}
      animate={{ opacity: 1, x: 0 }}
      className="space-y-8"
    >
      <div className="space-y-2 text-center md:text-left">
        <h2 className="text-2xl font-bold tracking-tight">Strategic Foundation</h2>
        <p className="text-muted-foreground text-sm">
          Define the purpose and mission your content strategy will serve.
        </p>
      </div>

      <div className="space-y-6">
        <div className="space-y-2">
          <Label htmlFor="workspace-name" className="flex items-center gap-2 font-bold text-gray-900">
            <Rocket className="size-4" /> Workspace Name
            <FieldInfo content="The public name of your workspace as it will appear in your dashboard and reports." />
          </Label>
          <Input
            id="workspace-name"
            placeholder="e.g. Hive Collective Main"
            className={cn(fieldStyles, "h-12")}
          />
        </div>

        <div className="space-y-2">
          <Label htmlFor="workspace-purpose" className="flex items-center gap-2 font-bold text-gray-900">
            <Target className="size-4" /> Workspace Purpose
            <FieldInfo content="Describe why this workspace exists and what the primary goal of your content strategy is." />
          </Label>
          <Textarea
            id="workspace-purpose"
            placeholder="What is the primary reason this workspace exists?"
            className={cn(fieldStyles, "min-h-[100px] py-4")}
          />
        </div>

        <div className="space-y-2">
          <Label htmlFor="mission" className="flex items-center gap-2 font-bold text-gray-900">
            <Shield className="size-4" /> Mission
            <FieldInfo content="Your long-term objective. What impact do you want your workspace to have?" />
          </Label>
          <Textarea
            id="mission"
            placeholder="What do you aim to achieve in the long term?"
            className={cn(fieldStyles, "min-h-[100px] py-4")}
          />
        </div>
      </div>
    </motion.div>
  );
}
