// apps/blinksocial-web/src/app/pages/new-workspace/steps/step-audience/step-audience.component.ts
import { Component, inject } from '@angular/core';
import { NewWorkspaceFormService } from '../../new-workspace-form.service';
import { OutlineButtonComponent } from '../../../../shared/outline-button/outline-button.component';

@Component({
  selector: 'app-step-audience',
  imports: [OutlineButtonComponent],
  templateUrl: './step-audience.component.html',
  styleUrl: './step-audience.component.scss',
})
export class StepAudienceComponent {
  protected readonly formService = inject(NewWorkspaceFormService);
}

<div class="step-audience">
  <div class="step-header">
    <h2>Audience Segments</h2>
    <p class="step-subtitle">Name the groups you're creating content for. You'll define full segment details in the Strategy section.</p>
  </div>

  <div class="callout">
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="callout-icon"><circle cx="12" cy="12" r="10"/><path d="M12 16v-4"/><path d="M12 8h.01"/></svg>
    <p>Keep this simple — just names for now. Detailed personas, pain points, and journey stages are built in the Strategy section.</p>
  </div>

  <div class="segments-list">
    @for (segment of formService.audienceSegments(); track segment.id) {
      <div class="segment-row">
        <input
          type="text"
          class="field-input segment-input"
          placeholder="e.g. Early-stage founders"
          [value]="segment.name"
          (input)="formService.updateSegmentName(segment.id, $any($event.target).value)"
        />
        <button class="remove-segment" (click)="formService.removeSegment(segment.id)">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M18 6 6 18"/><path d="m6 6 12 12"/></svg>
        </button>
      </div>
    }
  </div>

  @if (formService.audienceSegments().length < 6) {
    <div class="add-segment-wrapper">
      <app-outline-button (clicked)="formService.addSegment()">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12h14"/><path d="M12 5v14"/></svg>
        Add Segment
      </app-outline-button>
    </div>
  }
</div>

// figma/src/app/components/steps/StepAudience.tsx
import React, { useState } from "react";
import { Plus, X, Info } from "lucide-react";
import { Button } from "@/app/components/ui/button";
import { Input } from "@/app/components/ui/input";
import { motion, AnimatePresence } from "motion/react";
import { cn } from "@/lib/utils";

const fieldStyles = "bg-[#f3f4f6] border-none shadow-none focus-visible:ring-1 focus-visible:ring-gray-200 focus-visible:bg-[#edeff2] transition-colors";

interface Segment {
  id: number;
  name: string;
}

export function StepAudience() {
  const [segments, setSegments] = useState<Segment[]>([
    { id: 1, name: "" },
    { id: 2, name: "" },
  ]);

  const addSegment = () => {
    if (segments.length >= 6) return;
    setSegments((prev) => [...prev, { id: Date.now(), name: "" }]);
  };

  const removeSegment = (id: number) => {
    if (segments.length <= 1) return;
    setSegments((prev) => prev.filter((s) => s.id !== id));
  };

  const updateSegment = (id: number, name: string) => {
    setSegments((prev) => prev.map((s) => (s.id === id ? { ...s, name } : s)));
  };

  return (
    <motion.div
      initial={{ opacity: 0, x: 20 }}
      animate={{ opacity: 1, x: 0 }}
      className="space-y-8"
    >
      <div className="space-y-2 text-center md:text-left">
        <h2 className="text-2xl font-bold tracking-tight">Audience Segments</h2>
        <p className="text-muted-foreground text-sm">
          Name the groups you're creating content for. You'll define full segment details in the Strategy section.
        </p>
      </div>

      {/* Callout */}
      <div className="flex items-start gap-3 bg-amber-50 border border-amber-200 rounded-lg px-4 py-3">
        <Info className="size-4 text-amber-600 shrink-0 mt-0.5" />
        <p className="text-sm text-amber-800">
          Keep this simple — just names for now. Detailed personas, pain points, and journey stages are built in the Strategy section.
        </p>
      </div>

      <div className="space-y-3">
        <AnimatePresence mode="popLayout">
          {segments.map((segment) => (
            <motion.div
              key={segment.id}
              layout
              initial={{ opacity: 0, y: 8 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.95 }}
              className="flex items-center gap-3"
            >
              <Input
                value={segment.name}
                onChange={(e) => updateSegment(segment.id, e.target.value)}
                placeholder="e.g. Early-stage founders"
                className={cn(fieldStyles, "h-11 flex-1")}
              />
              {segments.length > 1 && (
                <button
                  onClick={() => removeSegment(segment.id)}
                  className="size-8 flex items-center justify-center text-muted-foreground hover:text-destructive rounded transition-colors shrink-0"
                >
                  <X className="size-4" />
                </button>
              )}
            </motion.div>
          ))}
        </AnimatePresence>
      </div>

      {segments.length < 6 && (
        <Button
          variant="outline"
          size="sm"
          className="gap-2 text-[#d94e33] border-[#d94e33] hover:bg-[#d94e33]/5"
          onClick={addSegment}
        >
          <Plus className="size-4" /> Add Segment
        </Button>
      )}
    </motion.div>
  );
}
