// apps/blinksocial-web/src/app/pages/new-workspace/steps/step-platform-config/step-platform-config.component.ts
import { Component, inject } from '@angular/core';
import { NewWorkspaceFormService } from '../../new-workspace-form.service';

@Component({
  selector: 'app-step-platform-config',
  templateUrl: './step-platform-config.component.html',
  styleUrl: './step-platform-config.component.scss',
})
export class StepPlatformConfigComponent {
  protected readonly formService = inject(NewWorkspaceFormService);

  readonly PLATFORMS = [
    'YouTube', 'LinkedIn', 'Twitter/X', 'Instagram',
    'Facebook', 'Slack', 'Discord',
  ];
}

<div class="step-platform-config">
  <div class="step-header">
    <h2>Platform Configuration</h2>
    <p class="step-subtitle">Set up global rules and individual platform strategies.</p>
  </div>

  <!-- Global Rules -->
  <div class="global-rules">
    <div class="global-rules-header">Global Rules</div>
    <div class="global-rules-body">
      <div class="global-grid">
        <div class="field-group">
          <label class="field-label-sm" for="default-platform">Default Platform</label>
          <select id="default-platform" class="field-select" [value]="formService.defaultPlatform()" (change)="formService.defaultPlatform.set($any($event.target).value)">
            @for (p of PLATFORMS; track p) {
              <option [value]="p">{{ p }}</option>
            }
          </select>
        </div>
        <div class="field-group">
          <label class="field-label-sm" for="max-ideas">Max Ideas Per Month</label>
          <input id="max-ideas" type="number" class="field-input" [value]="formService.maxIdeasPerMonth()" (input)="formService.maxIdeasPerMonth.set(+$any($event.target).value)" />
        </div>
      </div>

      <div class="toggles-row">
        <button class="toggle-card toggle-content-warning" (click)="formService.toggleContentWarning()">
          <div class="toggle-info">
            <span class="toggle-title">Content Warning</span>
            <span class="toggle-desc">Manual review trigger</span>
          </div>
          <div class="toggle-switch" [class.toggle-on]="formService.contentWarning()">
            <div class="toggle-knob"></div>
          </div>
        </button>
        <button class="toggle-card toggle-ai-disclaimer" (click)="formService.toggleAiDisclaimer()">
          <div class="toggle-info">
            <span class="toggle-title">AI Disclaimer</span>
            <span class="toggle-desc">Always include label</span>
          </div>
          <div class="toggle-switch" [class.toggle-on]="formService.aiDisclaimer()">
            <div class="toggle-knob"></div>
          </div>
        </button>
      </div>
    </div>
  </div>

  <!-- Platform List -->
  <div class="platforms-section">
    <span class="section-label">Active Platforms</span>
    <div class="platforms-list">
      @for (platform of PLATFORMS; track platform) {
        <details class="platform-item">
          <summary class="platform-header">
            <div class="platform-left">
              <div class="platform-icon" [class.platform-icon-active]="formService.isEnabled(platform)">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="18" cy="5" r="3"/><circle cx="6" cy="12" r="3"/><circle cx="18" cy="19" r="3"/><line x1="8.59" x2="15.42" y1="13.51" y2="17.49"/><line x1="15.41" x2="8.59" y1="6.51" y2="10.49"/></svg>
              </div>
              <span class="platform-name" [class.platform-name-muted]="!formService.isEnabled(platform)">{{ platform }}</span>
              <span class="platform-badge" [class.badge-active]="formService.isEnabled(platform)">
                {{ formService.isEnabled(platform) ? 'ACTIVE' : 'OFF' }}
              </span>
            </div>
            <button class="platform-toggle" (click)="formService.togglePlatform(platform); $event.preventDefault()">
              <div class="toggle-switch" [class.toggle-on]="formService.isEnabled(platform)">
                <div class="toggle-knob"></div>
              </div>
            </button>
          </summary>
          <div class="platform-details" [class.platform-disabled]="!formService.isEnabled(platform)">
            <div class="detail-section">
              <h4 class="detail-heading">
                <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m16 13 5.223 3.482a.5.5 0 0 0 .777-.416V7.87a.5.5 0 0 0-.752-.432L16 10.5"/><rect x="2" y="6" width="14" height="12" rx="2"/></svg>
                Video Specs
              </h4>
              <div class="detail-grid">
                <div class="detail-field">
                  <span class="detail-label">Aspect Ratio</span>
                  <select class="field-select-sm">
                    <option>16:9</option>
                    <option>9:16</option>
                  </select>
                </div>
                <div class="detail-field">
                  <span class="detail-label">Video Res</span>
                  <select class="field-select-sm">
                    <option>1080p</option>
                    <option>720p</option>
                  </select>
                </div>
                <div class="detail-field">
                  <span class="detail-label">Thumb Res</span>
                  <select class="field-select-sm">
                    <option>1280x720</option>
                  </select>
                </div>
              </div>
            </div>

            <div class="detail-section">
              <h4 class="detail-heading">
                <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg>
                Schedule
              </h4>
              <div class="detail-grid-2">
                <div class="detail-field">
                  <span class="detail-label">Frequency</span>
                  <select class="field-select-sm"><option>Daily</option></select>
                </div>
                <div class="detail-field">
                  <span class="detail-label">Timezone</span>
                  <select class="field-select-sm"><option>UTC</option></select>
                </div>
              </div>
            </div>

            <div class="detail-section">
              <h4 class="detail-heading">
                <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect width="7" height="7" x="14" y="3" rx="1"/><rect width="7" height="7" x="3" y="3" rx="1"/><rect width="7" height="7" x="14" y="14" rx="1"/><rect width="7" height="7" x="3" y="14" rx="1"/></svg>
                AI Styling
              </h4>
              <div class="detail-field">
                <span class="detail-label">Content Style</span>
                <input type="text" class="field-input-sm" value="documentary" />
              </div>
              <div class="detail-field">
                <span class="detail-label">Design Prompt Suffix</span>
                <textarea class="field-textarea-sm">Bold, high-contrast design. 16:9 format.</textarea>
              </div>
            </div>
          </div>
        </details>
      }
    </div>
  </div>
</div>

// figma/src/app/components/steps/StepPlatformConfig.tsx
import React from "react";
import { Label } from "@/app/components/ui/label";
import { Input } from "@/app/components/ui/input";
import { Switch } from "@/app/components/ui/switch";
import { 
  Accordion, 
  AccordionContent, 
  AccordionItem, 
  AccordionTrigger 
} from "@/app/components/ui/accordion";
import { Badge } from "@/app/components/ui/badge";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/app/components/ui/select";
import { Card, CardContent, CardHeader, CardTitle } from "@/app/components/ui/card";
import { Textarea } from "@/app/components/ui/textarea";
import { Button } from "@/app/components/ui/button";
import { motion } from "motion/react";
import { Share2, Video, Clock, Layout, Type, X, Plus } from "lucide-react";
import { cn } from "@/lib/utils";
import { FieldInfo } from "@/app/components/FieldInfo";

export function StepPlatformConfig() {
  const [enabledPlatforms, setEnabledPlatforms] = React.useState<string[]>(["YouTube", "LinkedIn"]);

  const togglePlatform = (platform: string) => {
    setEnabledPlatforms(prev => 
      prev.includes(platform) ? prev.filter(p => p !== platform) : [...prev, platform]
    );
  };

  const platforms = ["YouTube", "LinkedIn", "Twitter/X", "Instagram", "Facebook", "Slack", "Discord"];

  return (
    <motion.div
      initial={{ opacity: 0, x: 20 }}
      animate={{ opacity: 1, x: 0 }}
      className="space-y-8"
    >
      <div className="space-y-2 text-center md:text-left">
        <h2 className="text-2xl font-bold tracking-tight">Platform Configuration</h2>
        <p className="text-muted-foreground text-sm">
          Set up global rules and individual platform strategies.
        </p>
      </div>

      <div className="space-y-6">
        {/* Global Settings */}
        <Card className="border shadow-sm bg-white/50 backdrop-blur-sm">
          <CardHeader className="pb-4 border-b">
            <CardTitle className="text-sm font-semibold uppercase tracking-wider text-muted-foreground">Global Rules</CardTitle>
          </CardHeader>
          <CardContent className="pt-6 space-y-6">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="space-y-2">
                <Label className="text-xs flex items-center gap-2">
                  Default Platform
                  <FieldInfo content="The primary platform that will be pre-selected for new content." />
                </Label>
                <Select defaultValue="youtube">
                  <SelectTrigger className="h-10">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    {platforms.map(p => <SelectItem key={p} value={p.toLowerCase()}>{p}</SelectItem>)}
                  </SelectContent>
                </Select>
              </div>
              <div className="space-y-2">
                <Label className="text-xs flex items-center gap-2">
                  Max Ideas Per Month
                  <FieldInfo content="Set a cap on the number of AI-generated content ideas per month." />
                </Label>
                <Input type="number" defaultValue={30} className="h-10" />
              </div>
            </div>
            
            <div className="flex flex-col sm:flex-row gap-4">
              <div className="flex items-center justify-between border p-3 rounded-lg flex-1 bg-white">
                <div className="space-y-0.5">
                  <p className="text-xs font-medium flex items-center gap-2">
                    Content Warning
                    <FieldInfo content="Toggle manual review trigger for content that may need a warning." />
                  </p>
                  <p className="text-[10px] text-muted-foreground">Manual review trigger</p>
                </div>
                <Switch />
              </div>
              <div className="flex items-center justify-between border p-3 rounded-lg flex-1 bg-white">
                <div className="space-y-0.5">
                  <p className="text-xs font-medium flex items-center gap-2">
                    AI Disclaimer
                    <FieldInfo content="Automatically include a label stating content was generated by AI." />
                  </p>
                  <p className="text-[10px] text-muted-foreground">Always include label</p>
                </div>
                <Switch defaultChecked />
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Platforms Accordion */}
        <div className="space-y-3">
          <Label className="text-sm font-semibold px-1">Active Platforms</Label>
          <Accordion type="multiple" className="w-full space-y-2">
            {platforms.map((platform) => {
              const isActive = enabledPlatforms.includes(platform);
              return (
                <AccordionItem key={platform} value={platform} className="border rounded-xl bg-white overflow-hidden shadow-sm">
                  <div className="flex items-center justify-between px-4 relative">
                    <AccordionTrigger className="hover:no-underline py-4 flex-1">
                      <div className="flex items-center gap-3">
                        <div className={cn(
                          "size-8 rounded-lg flex items-center justify-center transition-colors",
                          isActive ? "bg-[#d94e33]/10 text-[#d94e33]" : "bg-gray-100 text-gray-400"
                        )}>
                          <Share2 className="size-4" />
                        </div>
                        <span className={cn("font-medium text-sm", !isActive && "text-muted-foreground")}>{platform}</span>
                        <Badge variant={isActive ? "default" : "outline"} className={cn(
                          "text-[9px] h-4.5 px-1.5",
                          isActive ? "bg-green-500 text-white border-transparent" : "text-muted-foreground/60 border-gray-200"
                        )}>
                          {isActive ? "ACTIVE" : "OFF"}
                        </Badge>
                      </div>
                    </AccordionTrigger>
                    <div className="absolute right-10 top-1/2 -translate-y-1/2 z-10 scale-75">
                      <Switch 
                        checked={isActive} 
                        onCheckedChange={() => togglePlatform(platform)}
                      />
                    </div>
                  </div>

                  <AccordionContent className={cn("px-4 pb-6 space-y-8", !isActive && "opacity-40 grayscale-[0.5] pointer-events-none")}>
                    <div className="h-px bg-gray-100 -mx-4 mb-4" />
                    
                    {/* Video Settings */}
                    <div className="space-y-4">
                      <h4 className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground flex items-center gap-2">
                        <Video className="size-3" /> Video Specs
                      </h4>
                      <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
                        <div className="space-y-1.5">
                          <Label className="text-[10px] flex items-center gap-2">
                            Aspect Ratio
                            <FieldInfo content="The preferred width-to-height ratio for video content." />
                          </Label>
                          <Select defaultValue="16:9">
                            <SelectTrigger className="h-8 text-xs"><SelectValue /></SelectTrigger>
                            <SelectContent>
                              <SelectItem value="16:9">16:9</SelectItem>
                              <SelectItem value="9:16">9:16</SelectItem>
                            </SelectContent>
                          </Select>
                        </div>
                        <div className="space-y-1.5">
                          <Label className="text-[10px] flex items-center gap-2">
                            Video Res
                            <FieldInfo content="The vertical resolution of the exported video." />
                          </Label>
                          <Select defaultValue="1080p">
                            <SelectTrigger className="h-8 text-xs"><SelectValue /></SelectTrigger>
                            <SelectContent><SelectItem value="1080p">1080p</SelectItem></SelectContent>
                          </Select>
                        </div>
                        <div className="space-y-1.5">
                          <Label className="text-[10px] flex items-center gap-2">
                            Thumb Res
                            <FieldInfo content="The resolution for generated thumbnail images." />
                          </Label>
                          <Select defaultValue="1280">
                            <SelectTrigger className="h-8 text-xs"><SelectValue /></SelectTrigger>
                            <SelectContent><SelectItem value="1280">1280x720</SelectItem></SelectContent>
                          </Select>
                        </div>
                      </div>
                    </div>

                    {/* Schedule Settings */}
                    <div className="space-y-4">
                      <h4 className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground flex items-center gap-2">
                        <Clock className="size-3" /> Schedule
                      </h4>
                      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                        <div className="space-y-1.5">
                          <Label className="text-[10px] flex items-center gap-2">
                            Frequency
                            <FieldInfo content="How often content should be posted to this platform." />
                          </Label>
                          <Select defaultValue="daily">
                            <SelectTrigger className="h-8 text-xs"><SelectValue /></SelectTrigger>
                            <SelectContent><SelectItem value="daily">Daily</SelectItem></SelectContent>
                          </Select>
                        </div>
                        <div className="space-y-1.5">
                          <Label className="text-[10px] flex items-center gap-2">
                            Timezone
                            <FieldInfo content="The timezone used for calculating optimal post times." />
                          </Label>
                          <Select defaultValue="utc">
                            <SelectTrigger className="h-8 text-xs"><SelectValue /></SelectTrigger>
                            <SelectContent><SelectItem value="utc">UTC</SelectItem></SelectContent>
                          </Select>
                        </div>
                      </div>
                      <div className="space-y-2">
                        <Label className="text-[10px] flex items-center gap-2">
                          Peak Times
                          <FieldInfo content="Specific times of day when your audience is most active." />
                        </Label>
                        <div className="flex flex-wrap gap-1.5">
                          {["19:00", "21:00"].map(t => (
                            <Badge key={t} variant="secondary" className="h-6 gap-1 text-[10px] bg-blue-50 text-blue-600 border-blue-100">
                              {t} <X className="size-2.5" />
                            </Badge>
                          ))}
                          <Button variant="outline" size="sm" className="h-6 px-2 text-[10px] border-dashed">
                            <Plus className="size-2.5 mr-1" /> Add
                          </Button>
                        </div>
                      </div>
                    </div>

                    {/* AI Generation */}
                    <div className="space-y-4">
                      <h4 className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground flex items-center gap-2">
                        <Layout className="size-3" /> AI Styling
                      </h4>
                      <div className="space-y-2">
                        <Label className="text-[10px] flex items-center gap-2">
                          <Type className="size-2.5" /> Content Style
                          <FieldInfo content="The creative style or genre for AI-generated content." />
                        </Label>
                        <Input defaultValue="documentary" className="h-8 text-xs" />
                      </div>
                      <div className="space-y-2">
                        <Label className="text-[10px] flex items-center gap-2">
                          Design Prompt Suffix
                          <FieldInfo content="Text added to the end of every design prompt for this platform." />
                        </Label>
                        <Textarea 
                          className="min-h-[60px] text-xs"
                          defaultValue="Bold, high-contrast design. 16:9 format."
                        />
                      </div>
                    </div>
                  </AccordionContent>
                </AccordionItem>
              );
            })}
          </Accordion>
        </div>
      </div>
    </motion.div>
  );
}
