// apps/blinksocial-web/src/app/pages/new-workspace/steps/step-brand-positioning/step-brand-positioning.component.ts
import { Component, inject, signal } from '@angular/core';
import { NewWorkspaceFormService } from '../../new-workspace-form.service';
import { TooltipComponent } from '../../../../shared/tooltip/tooltip.component';
import { OutlineButtonComponent } from '../../../../shared/outline-button/outline-button.component';

@Component({
  selector: 'app-step-brand-positioning',
  imports: [TooltipComponent, OutlineButtonComponent],
  templateUrl: './step-brand-positioning.component.html',
  styleUrl: './step-brand-positioning.component.scss',
})
export class StepBrandPositioningComponent {
  protected readonly formService = inject(NewWorkspaceFormService);
  readonly isGenerating = signal(false);

  readonly TONE_OPTIONS = [
    'Authoritative', 'Playful', 'Educational', 'Inspirational',
    'Conversational', 'Bold', 'Empathetic', 'Direct',
  ];

  generatePositioningStatement(): void {
    const bp = this.formService.brandPositioning();
    if (!bp.targetCustomer && !bp.problemSolved && !bp.solution && !bp.differentiator) return;

    this.isGenerating.set(true);
    setTimeout(() => {
      const statement = `For ${bp.targetCustomer || '[target customer]'} who ${bp.problemSolved || '[face this problem]'}, ${bp.solution || '[our solution]'} is the answer that ${bp.differentiator || '[sets us apart]'}.`;
      this.formService.updateBrandPositioning('positioningStatement', statement);
      this.isGenerating.set(false);
    }, 1500);
  }
}

<div class="step-brand-positioning">
  <div class="step-header">
    <h2>Brand Positioning &amp; Voice</h2>
    <p class="step-subtitle">Define how you communicate and what makes you different.</p>
  </div>

  <!-- Section A: Brand Positioning -->
  <div class="section">
    <div class="section-header">
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="section-icon"><circle cx="12" cy="12" r="10"/><line x1="22" x2="18" y1="12" y2="12"/><line x1="6" x2="2" y1="12" y2="12"/><line x1="12" x2="12" y1="6" y2="2"/><line x1="12" x2="12" y1="22" y2="18"/></svg>
      <span class="section-label">Brand Positioning</span>
      <app-tooltip text="Your positioning defines who you serve, what problem you solve, and why you're different. This guides every piece of content." />
    </div>

    <div class="positioning-fields">
      <div class="field-group">
        <span class="field-label">Who is your target customer?</span>
        <input type="text" class="field-input" placeholder="e.g. Women 40+ navigating midlife wellness" [value]="formService.brandPositioning().targetCustomer" (input)="formService.updateBrandPositioning('targetCustomer', $any($event.target).value)" />
      </div>
      <div class="field-group">
        <span class="field-label">What problem do they have?</span>
        <input type="text" class="field-input" placeholder="e.g. Overwhelmed by conflicting fitness advice" [value]="formService.brandPositioning().problemSolved" (input)="formService.updateBrandPositioning('problemSolved', $any($event.target).value)" />
      </div>
      <div class="field-group">
        <span class="field-label">What's your solution?</span>
        <input type="text" class="field-input" placeholder="e.g. A movement-first wellness community with expert guidance" [value]="formService.brandPositioning().solution" (input)="formService.updateBrandPositioning('solution', $any($event.target).value)" />
      </div>
      <div class="field-group">
        <span class="field-label">What makes you different?</span>
        <input type="text" class="field-input" placeholder="e.g. We combine clinical expertise with authentic community" [value]="formService.brandPositioning().differentiator" (input)="formService.updateBrandPositioning('differentiator', $any($event.target).value)" />
      </div>

      <app-outline-button (clicked)="generatePositioningStatement()" [disabled]="isGenerating()">
        @if (isGenerating()) {
          <svg class="spin" xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 12a9 9 0 1 1-6.219-8.56"/></svg>
          Generating...
        } @else {
          <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M9.937 15.5A2 2 0 0 0 8.5 14.063l-6.135-1.582a.5.5 0 0 1 0-.962L8.5 9.936A2 2 0 0 0 9.937 8.5l1.582-6.135a.5.5 0 0 1 .963 0L14.063 8.5A2 2 0 0 0 15.5 9.937l6.135 1.581a.5.5 0 0 1 0 .964L15.5 14.063a2 2 0 0 0-1.437 1.437l-1.582 6.135a.5.5 0 0 1-.963 0z"/></svg>
          Generate Positioning Statement
        }
      </app-outline-button>
    </div>

    @if (formService.brandPositioning().positioningStatement) {
      <div class="field-group">
        <span class="field-label">Positioning Statement</span>
        <textarea class="field-textarea" [value]="formService.brandPositioning().positioningStatement" (input)="formService.updateBrandPositioning('positioningStatement', $any($event.target).value)"></textarea>
      </div>
    }
  </div>

  <div class="section-divider"></div>

  <!-- Section B: Voice & Tone -->
  <div class="section">
    <div class="section-header">
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="section-icon-muted"><path d="m11 7.601-5.994 8.19a1 1 0 0 0 .1 1.298l.817.818a1 1 0 0 0 1.314.087L15.09 12"/><path d="M16.5 21.174C15.5 20.5 14.372 20 13 20c-2.058 0-3.928 2.356-6 2-2.072-.356-2.775-3.369-1.5-4.5"/><circle cx="16" cy="7" r="5"/></svg>
      <span class="section-label">Brand Voice &amp; Tone</span>
      <app-tooltip text="How does your brand sound? Describe your personality and communication style." />
    </div>

    <div class="voice-fields">
      <textarea class="field-textarea" placeholder="e.g. Professional but approachable. We explain complex topics simply without being condescending." [value]="formService.brandVoice()" (input)="formService.brandVoice.set($any($event.target).value)"></textarea>

      <div class="tone-tags">
        @for (tag of TONE_OPTIONS; track tag) {
          <button
            class="tone-tag"
            [class.tone-selected]="formService.isToneTagSelected(tag)"
            (click)="formService.toggleToneTag(tag)"
          >
            {{ tag }}
          </button>
        }
      </div>
    </div>
  </div>
</div>

// figma/src/app/components/steps/StepBrandPositioning.tsx
import React, { useState } from "react";
import { Crosshair, Mic2, Sparkles, Loader2 } from "lucide-react";
import { Button } from "@/app/components/ui/button";
import { Input } from "@/app/components/ui/input";
import { Label } from "@/app/components/ui/label";
import { Textarea } from "@/app/components/ui/textarea";
import { motion } from "motion/react";
import { cn } from "@/lib/utils";
import { FieldInfo } from "@/app/components/FieldInfo";
import { toast } from "sonner";

const fieldStyles = "bg-[#f3f4f6] border-none shadow-none focus-visible:ring-1 focus-visible:ring-gray-200 focus-visible:bg-[#edeff2] transition-colors";

const TONE_OPTIONS = [
  "Authoritative",
  "Playful",
  "Educational",
  "Inspirational",
  "Conversational",
  "Bold",
  "Empathetic",
  "Direct",
];

interface StepBrandPositioningProps {
  workspaceName?: string;
}

export function StepBrandPositioning({ workspaceName = "your brand" }: StepBrandPositioningProps) {
  const [targetCustomer, setTargetCustomer] = useState("");
  const [problemSolved, setProblemSolved] = useState("");
  const [solution, setSolution] = useState("");
  const [differentiator, setDifferentiator] = useState("");
  const [positioningStatement, setPositioningStatement] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);

  const [brandVoice, setBrandVoice] = useState("");
  const [selectedTones, setSelectedTones] = useState<string[]>([]);

  const handleGenerateStatement = () => {
    setIsGenerating(true);
    setTimeout(() => {
      setIsGenerating(false);
      const statement = `For ${targetCustomer || "[target customer]"} who ${problemSolved || "[problem solved]"}, ${workspaceName} is the ${solution || "[solution]"} that ${differentiator || "[differentiator]"}.`;
      setPositioningStatement(statement);
      toast.success("Positioning statement generated");
    }, 1500);
  };

  const toggleTone = (tone: string) => {
    setSelectedTones((prev) =>
      prev.includes(tone) ? prev.filter((t) => t !== tone) : [...prev, tone]
    );
  };

  return (
    <motion.div
      initial={{ opacity: 0, x: 20 }}
      animate={{ opacity: 1, x: 0 }}
      className="space-y-8"
    >
      <div className="space-y-2 text-center md:text-left">
        <h2 className="text-2xl font-bold tracking-tight">Brand Positioning & Voice</h2>
        <p className="text-muted-foreground text-sm">
          Define how you communicate and what makes you different.
        </p>
      </div>

      {/* Section A — Brand Positioning */}
      <div className="space-y-5">
        <div className="flex items-center gap-2">
          <Crosshair className="size-4 text-[#d94e33]" />
          <span className="font-bold text-gray-900">Brand Positioning</span>
          <FieldInfo content="Your positioning defines who you serve, what problem you solve, and why you're different. This guides every piece of content." />
        </div>

        <div className="space-y-4">
          <div className="space-y-2">
            <Label className="text-xs font-bold uppercase tracking-wider text-muted-foreground">
              Who is your target customer?
            </Label>
            <Input
              value={targetCustomer}
              onChange={(e) => setTargetCustomer(e.target.value)}
              placeholder="e.g. Women 40+ navigating midlife wellness"
              className={cn(fieldStyles, "h-11")}
            />
          </div>

          <div className="space-y-2">
            <Label className="text-xs font-bold uppercase tracking-wider text-muted-foreground">
              What problem do they have?
            </Label>
            <Input
              value={problemSolved}
              onChange={(e) => setProblemSolved(e.target.value)}
              placeholder="e.g. Overwhelmed by conflicting fitness advice"
              className={cn(fieldStyles, "h-11")}
            />
          </div>

          <div className="space-y-2">
            <Label className="text-xs font-bold uppercase tracking-wider text-muted-foreground">
              What's your solution?
            </Label>
            <Input
              value={solution}
              onChange={(e) => setSolution(e.target.value)}
              placeholder="e.g. A movement-first wellness community with expert guidance"
              className={cn(fieldStyles, "h-11")}
            />
          </div>

          <div className="space-y-2">
            <Label className="text-xs font-bold uppercase tracking-wider text-muted-foreground">
              What makes you different?
            </Label>
            <Input
              value={differentiator}
              onChange={(e) => setDifferentiator(e.target.value)}
              placeholder="e.g. We combine clinical expertise with authentic community"
              className={cn(fieldStyles, "h-11")}
            />
          </div>

          <Button
            variant="outline"
            className="gap-2 text-[#d94e33] border-[#d94e33] hover:bg-[#d94e33]/5"
            onClick={handleGenerateStatement}
            disabled={isGenerating}
          >
            {isGenerating ? <Loader2 className="size-4 animate-spin" /> : <Sparkles className="size-4" />}
            Generate Positioning Statement
          </Button>

          {positioningStatement && (
            <div className="space-y-1.5">
              <Label className="text-xs font-bold uppercase tracking-wider text-muted-foreground">
                Positioning Statement
              </Label>
              <Textarea
                value={positioningStatement}
                onChange={(e) => setPositioningStatement(e.target.value)}
                className={cn(fieldStyles, "min-h-[80px] py-3 resize-none")}
              />
            </div>
          )}
        </div>
      </div>

      {/* Section B — Brand Voice */}
      <div className="space-y-5 pt-2 border-t">
        <div className="flex items-center gap-2 pt-4">
          <Mic2 className="size-4 text-gray-600" />
          <span className="font-bold text-gray-900">Brand Voice & Tone</span>
          <FieldInfo content="How does your brand sound? Describe your personality and communication style." />
        </div>

        <div className="space-y-4">
          <Textarea
            value={brandVoice}
            onChange={(e) => setBrandVoice(e.target.value)}
            placeholder="e.g. Professional but approachable. We explain complex topics simply without being condescending."
            className={cn(fieldStyles, "min-h-[100px] py-4 resize-none")}
          />

          <div className="flex flex-wrap gap-2">
            {TONE_OPTIONS.map((tone) => {
              const isSelected = selectedTones.includes(tone);
              return (
                <button
                  key={tone}
                  type="button"
                  onClick={() => toggleTone(tone)}
                  className={cn(
                    "px-3 py-1.5 rounded-full text-xs font-medium border transition-all",
                    isSelected
                      ? "bg-[#d94e33] border-[#d94e33] text-white"
                      : "bg-gray-50 border-gray-200 text-gray-600 hover:border-gray-300"
                  )}
                >
                  {tone}
                </button>
              );
            })}
          </div>
        </div>
      </div>
    </motion.div>
  );
}
