// apps/blinksocial-web/src/app/pages/new-workspace/steps/step-objectives/step-objectives.component.ts
import { Component, inject, signal } from '@angular/core';
import { NewWorkspaceFormService } from '../../new-workspace-form.service';
import { OutlineButtonComponent } from '../../../../shared/outline-button/outline-button.component';

@Component({
  selector: 'app-step-objectives',
  imports: [OutlineButtonComponent],
  templateUrl: './step-objectives.component.html',
  styleUrl: './step-objectives.component.scss',
})
export class StepObjectivesComponent {
  protected readonly formService = inject(NewWorkspaceFormService);
  readonly isSuggesting = signal(false);

  readonly CATEGORIES = [
    { value: 'growth', label: 'Growth', emoji: '\u{1F4C8}' },
    { value: 'revenue', label: 'Revenue', emoji: '\u{1F4B0}' },
    { value: 'awareness', label: 'Awareness', emoji: '\u{1F4E3}' },
    { value: 'trust', label: 'Trust', emoji: '\u{1F91D}' },
    { value: 'community', label: 'Community', emoji: '\u{1F465}' },
    { value: 'engagement', label: 'Engagement', emoji: '\u{26A1}' },
  ];

  suggestObjectives(): void {
    this.isSuggesting.set(true);
    setTimeout(() => {
      this.formService.businessObjectives.set([
        { id: Date.now(), category: 'growth', statement: 'Grow combined social following to 25,000', target: '25000', unit: 'followers', timeframe: 'Q4 2026' },
        { id: Date.now() + 1, category: 'engagement', statement: 'Achieve 5% average engagement rate across platforms', target: '5', unit: '%', timeframe: 'Q3 2026' },
      ]);
      this.isSuggesting.set(false);
    }, 1500);
  }
}

<div class="step-objectives">
  <div class="step-header">
    <h2>Business Objectives</h2>
    <p class="step-subtitle">What does success look like? Define 2–10 measurable goals that your content strategy will serve.</p>
  </div>

  <div class="callout">
    Everything in Blink — your pillars, audience, content, and performance — traces back to these objectives. Set them carefully.
  </div>

  <div class="objectives-list">
    @for (obj of formService.businessObjectives(); track obj.id) {
      <div class="objective-card">
        @if (formService.businessObjectives().length > 1) {
          <button class="remove-objective" (click)="formService.removeObjective(obj.id)">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M18 6 6 18"/><path d="m6 6 12 12"/></svg>
          </button>
        }

        <div class="field-group">
          <span class="field-label">Category</span>
          <div class="category-buttons">
            @for (cat of CATEGORIES; track cat.value) {
              <button
                class="category-btn"
                [class.category-selected]="obj.category === cat.value"
                (click)="formService.updateObjective(obj.id, 'category', cat.value)"
              >
                <span class="category-emoji">{{ cat.emoji }}</span>
                {{ cat.label }}
              </button>
            }
          </div>
        </div>

        <div class="field-group">
          <span class="field-label">Objective</span>
          <input type="text" class="field-input" placeholder="e.g. Grow Instagram following to 10,000" [value]="obj.statement" (input)="formService.updateObjective(obj.id, 'statement', $any($event.target).value)" />
        </div>

        <div class="objective-metrics">
          <div class="field-group">
            <span class="field-label">Target</span>
            <input type="number" class="field-input" placeholder="10000" [value]="obj.target" (input)="formService.updateObjective(obj.id, 'target', $any($event.target).value)" />
          </div>
          <div class="field-group">
            <span class="field-label">Unit</span>
            <input type="text" class="field-input" placeholder="followers" [value]="obj.unit" (input)="formService.updateObjective(obj.id, 'unit', $any($event.target).value)" />
          </div>
          <div class="field-group">
            <span class="field-label">Timeframe</span>
            <input type="text" class="field-input" placeholder="Q2 2026" [value]="obj.timeframe" (input)="formService.updateObjective(obj.id, 'timeframe', $any($event.target).value)" />
          </div>
        </div>
      </div>
    }
  </div>

  @if (formService.businessObjectives().length < 10) {
    <div class="add-objective-wrapper">
      <app-outline-button (clicked)="formService.addObjective()">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12h14"/><path d="M12 5v14"/></svg>
        Add Objective
      </app-outline-button>
    </div>
  }

  <div class="actions-row">
    <app-outline-button (clicked)="suggestObjectives()" [disabled]="isSuggesting()">
      @if (isSuggesting()) {
        <svg class="spin" xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 12a9 9 0 1 1-6.219-8.56"/></svg>
        Suggesting...
      } @else {
        <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M9.937 15.5A2 2 0 0 0 8.5 14.063l-6.135-1.582a.5.5 0 0 1 0-.962L8.5 9.936A2 2 0 0 0 9.937 8.5l1.582-6.135a.5.5 0 0 1 .963 0L14.063 8.5A2 2 0 0 0 15.5 9.937l6.135 1.581a.5.5 0 0 1 0 .964L15.5 14.063a2 2 0 0 0-1.437 1.437l-1.582 6.135a.5.5 0 0 1-.963 0z"/></svg>
        AI Suggest Objectives
      }
    </app-outline-button>
  </div>
</div>

// figma/src/app/components/steps/StepObjectives.tsx
import React, { useState } from "react";
import { Sparkles, Loader2, X, Plus } from "lucide-react";
import { Button } from "@/app/components/ui/button";
import { Input } from "@/app/components/ui/input";
import { Label } from "@/app/components/ui/label";
import type { BusinessObjective, ObjectiveCategory } from "@/app/components/content/types";
import { toast } from "sonner";
import { cn } from "@/lib/utils";

const CATEGORY_CONFIG: Record<ObjectiveCategory, { label: string; emoji: string }> = {
  growth:     { label: "Growth",     emoji: "📈" },
  revenue:    { label: "Revenue",    emoji: "💰" },
  awareness:  { label: "Awareness",  emoji: "📣" },
  trust:      { label: "Trust",      emoji: "🤝" },
  community:  { label: "Community",  emoji: "👥" },
  engagement: { label: "Engagement", emoji: "⚡" },
};

const MOCK_SUGGESTED: Omit<BusinessObjective, "id">[] = [
  {
    category: "growth",
    statement: "Grow combined social following to 25,000",
    target: 25000,
    unit: "followers",
    timeframe: "Q4 2026",
    status: "on-track",
  },
  {
    category: "engagement",
    statement: "Achieve 5% average engagement rate across platforms",
    target: 5,
    unit: "%",
    timeframe: "Q3 2026",
    status: "on-track",
  },
];

function newBlankObjective(): BusinessObjective {
  return {
    id: `obj-${Date.now()}-${Math.random().toString(36).slice(2)}`,
    category: "growth",
    statement: "",
    target: 0,
    unit: "",
    timeframe: "",
    status: "on-track",
  };
}

export function DEFAULT_OBJECTIVES(): BusinessObjective[] {
  return [newBlankObjective(), newBlankObjective()];
}

interface StepObjectivesProps {
  objectives: BusinessObjective[];
  onUpdateObjectives: (objectives: BusinessObjective[]) => void;
}

export function StepObjectives({ objectives, onUpdateObjectives }: StepObjectivesProps) {
  const [isSuggesting, setIsSuggesting] = useState(false);

  const updateObjective = (id: string, updates: Partial<BusinessObjective>) => {
    onUpdateObjectives(objectives.map((o) => (o.id === id ? { ...o, ...updates } : o)));
  };

  const removeObjective = (id: string) => {
    if (objectives.length <= 1) return;
    onUpdateObjectives(objectives.filter((o) => o.id !== id));
  };

  const addObjective = () => {
    if (objectives.length >= 4) return;
    onUpdateObjectives([...objectives, newBlankObjective()]);
  };

  const handleAISuggest = () => {
    setIsSuggesting(true);
    setTimeout(() => {
      setIsSuggesting(false);
      const suggested = MOCK_SUGGESTED.map((o) => ({
        ...o,
        id: `obj-${Date.now()}-${Math.random().toString(36).slice(2)}`,
      }));
      onUpdateObjectives([...objectives, ...suggested].slice(0, 4));
      toast.success("Objectives suggested — adjust to fit your goals");
    }, 2500);
  };

  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-2xl font-extrabold tracking-tight text-gray-900 mb-1">Business Objectives</h2>
        <p className="text-muted-foreground">
          What does success look like? Define 2–4 measurable goals that your content strategy will serve.
        </p>
      </div>

      <div className="bg-amber-50 border border-amber-200 rounded-lg px-4 py-3 text-sm text-amber-800">
        Everything in Blink — your pillars, audience, content, and performance — traces back to these objectives. Set them carefully.
      </div>

      <div className="space-y-4">
        {objectives.map((obj) => (
          <div key={obj.id} className="border border-gray-200 rounded-xl p-4 space-y-4 bg-white relative">
            {objectives.length > 1 && (
              <button
                className="absolute top-3 right-3 size-6 flex items-center justify-center text-muted-foreground hover:text-destructive rounded"
                onClick={() => removeObjective(obj.id)}
              >
                <X className="size-4" />
              </button>
            )}

            <div className="space-y-1.5">
              <Label className="text-xs font-bold uppercase tracking-wider text-muted-foreground">Category</Label>
              <div className="flex flex-wrap gap-2">
                {(Object.entries(CATEGORY_CONFIG) as [ObjectiveCategory, { label: string; emoji: string }][]).map(([cat, cfg]) => (
                  <button
                    key={cat}
                    onClick={() => updateObjective(obj.id, { category: cat })}
                    className={cn(
                      "flex items-center gap-1.5 px-3 py-1.5 rounded-full border text-sm transition-all",
                      obj.category === cat
                        ? "border-[#d94e33] bg-[#d94e33]/5 text-[#d94e33] font-medium"
                        : "border-gray-200 text-muted-foreground hover:border-gray-300"
                    )}
                  >
                    <span>{cfg.emoji}</span> {cfg.label}
                  </button>
                ))}
              </div>
            </div>

            <div className="space-y-1.5">
              <Label className="text-xs font-bold uppercase tracking-wider text-muted-foreground">Objective</Label>
              <Input
                value={obj.statement}
                onChange={(e) => updateObjective(obj.id, { statement: e.target.value })}
                placeholder="e.g. Grow Instagram following to 10,000"
              />
            </div>

            <div className="grid grid-cols-3 gap-3">
              <div className="space-y-1.5">
                <Label className="text-xs font-bold uppercase tracking-wider text-muted-foreground">Target</Label>
                <Input
                  type="number"
                  value={obj.target || ""}
                  onChange={(e) => updateObjective(obj.id, { target: Number(e.target.value) })}
                  placeholder="10000"
                />
              </div>
              <div className="space-y-1.5">
                <Label className="text-xs font-bold uppercase tracking-wider text-muted-foreground">Unit</Label>
                <Input
                  value={obj.unit}
                  onChange={(e) => updateObjective(obj.id, { unit: e.target.value })}
                  placeholder="followers"
                />
              </div>
              <div className="space-y-1.5">
                <Label className="text-xs font-bold uppercase tracking-wider text-muted-foreground">Timeframe</Label>
                <Input
                  value={obj.timeframe}
                  onChange={(e) => updateObjective(obj.id, { timeframe: e.target.value })}
                  placeholder="Q2 2026"
                />
              </div>
            </div>
          </div>
        ))}
      </div>

      <div className="flex items-center gap-3">
        {objectives.length < 4 && (
          <Button variant="outline" className="gap-2" onClick={addObjective}>
            <Plus className="size-4" /> Add Objective
          </Button>
        )}
        <Button
          variant="outline"
          className="gap-2 text-[#d94e33] border-[#d94e33] hover:bg-[#d94e33]/5"
          onClick={handleAISuggest}
          disabled={isSuggesting || objectives.length >= 4}
        >
          {isSuggesting ? <Loader2 className="size-4 animate-spin" /> : <Sparkles className="size-4" />}
          AI Suggest Objectives
        </Button>
      </div>
    </div>
  );
}
