// apps/blinksocial-web/src/app/pages/strategy-research/views/brand-voice/brand-voice.component.ts
import { Component, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import type {
  BrandVoiceData,
  VoiceAttribute,
  ToneContext,
  Platform,
} from '../../strategy-research.types';

const MOCK_VOICE_ATTRIBUTES: VoiceAttribute[] = [
  { id: 'va1', label: 'Empowering', description: 'We lift women up, never talk down to them.', doExample: 'You have everything it takes — let\'s unlock it together.', dontExample: 'You need to fix your relationship with your body.' },
  { id: 'va2', label: 'Knowledgeable but Accessible', description: 'Expert-backed but never jargon-heavy.', doExample: 'Estrogen affects your muscle recovery — here\'s what that means for your workouts.', dontExample: 'HRT-mediated myofibrillar protein synthesis rates indicate...' },
  { id: 'va3', label: 'Warm & Inclusive', description: 'Every woman in her 40s belongs here.', doExample: 'Whether you\'re a lifelong athlete or just rediscovering movement — this is your space.', dontExample: 'For women who are already committed to fitness.' },
  { id: 'va4', label: 'Honest & Real', description: 'No toxic positivity, no impossible standards.', doExample: 'Some days perimenopause wins. That\'s real. Here\'s how to adapt.', dontExample: 'Every day is an opportunity to crush it!' },
];

const MOCK_TONE_CONTEXTS: ToneContext[] = [
  { id: 'tc1', context: 'Educational', tone: 'Clear, authoritative, relatable', example: 'Here\'s what\'s actually happening in your body during perimenopause — and what you can do about it today.' },
  { id: 'tc2', context: 'Motivational', tone: 'Energetic, affirming, forward-looking', example: 'Your strongest decade might just be the one you\'re stepping into right now.' },
  { id: 'tc3', context: 'Community', tone: 'Warm, conversational, curious', example: 'What\'s been your biggest shift in how you train since turning 40?' },
  { id: 'tc4', context: 'Promotional', tone: 'Honest and benefit-led — never pushy', example: 'We built this program for the woman who knows what she wants but needs the right tools.' },
];

const MOCK_VOCAB = {
  preferred: ['perimenopause', 'hormonal shift', 'movement', 'reclaim', 'adapt', 'community', 'evidence-backed', 'sustainable'],
  avoid: ['anti-aging', 'fight', 'battle', 'fix your body', 'before & after', 'dramatic results'],
};

const MOCK_PLATFORM_SUGGESTIONS: Record<string, string> = {
  instagram: 'Warm, visual storytelling. Use emojis sparingly. Captions can be medium-length with a strong hook.',
  tiktok: 'Fast-paced and conversational — mirror trending audio language. Hook within 2 seconds.',
  youtube: 'Thorough and evidence-backed. Viewers opt in for depth — reward them with real value.',
  facebook: 'Community-first. Ask questions, celebrate wins, invite discussion.',
  linkedin: 'Professional but human — share expertise with personal context.',
};

const ALL_PLATFORMS: Platform[] = ['instagram', 'tiktok', 'youtube', 'facebook', 'linkedin'];

@Component({
  selector: 'app-brand-voice',
  imports: [CommonModule, FormsModule],
  templateUrl: './brand-voice.component.html',
  styleUrl: './brand-voice.component.scss',
})
export class BrandVoiceComponent {
  readonly data = signal<BrandVoiceData>({
    missionStatement: '',
    voiceAttributes: [],
    toneByContext: [],
    platformToneAdjustments: ALL_PLATFORMS.map(p => ({ platform: p, adjustment: '' })),
    vocabulary: { preferred: [], avoid: [] },
  });

  readonly isDraftingMission = signal(false);
  readonly isGeneratingAttributes = signal(false);
  readonly suggestingPlatform = signal<Platform | null>(null);

  // Editing state for voice attributes
  readonly editingAttributeId = signal<string | null>(null);
  readonly editAttribute = signal<VoiceAttribute>({ id: '', label: '', description: '', doExample: '', dontExample: '' });

  // Editing state for tone contexts
  readonly editingToneId = signal<string | null>(null);
  readonly editTone = signal<ToneContext>({ id: '', context: '', tone: '', example: '' });

  // Vocab input state
  readonly newPreferredWord = signal('');
  readonly newAvoidWord = signal('');

  readonly platformLabels: Record<Platform, string> = {
    instagram: 'Instagram',
    tiktok: 'TikTok',
    youtube: 'YouTube',
    facebook: 'Facebook',
    linkedin: 'LinkedIn',
  };

  // --- Mission Statement ---

  draftMission(): void {
    this.isDraftingMission.set(true);
    setTimeout(() => {
      this.data.update(d => ({
        ...d,
        missionStatement: 'Empower women over 40 to reclaim their strength, vitality, and confidence through evidence-backed fitness, nutrition, and community — because your best years are not behind you.',
      }));
      this.isDraftingMission.set(false);
    }, 2000);
  }

  updateMission(value: string): void {
    this.data.update(d => ({ ...d, missionStatement: value }));
  }

  // --- Voice Attributes ---

  generateAttributes(): void {
    this.isGeneratingAttributes.set(true);
    setTimeout(() => {
      this.data.update(d => ({ ...d, voiceAttributes: [...d.voiceAttributes, ...MOCK_VOICE_ATTRIBUTES] }));
      this.isGeneratingAttributes.set(false);
    }, 2000);
  }

  startAddAttribute(): void {
    const newId = `va-${Date.now()}`;
    this.editingAttributeId.set(newId);
    this.editAttribute.set({ id: newId, label: '', description: '', doExample: '', dontExample: '' });
  }

  startEditAttribute(attr: VoiceAttribute): void {
    this.editingAttributeId.set(attr.id);
    this.editAttribute.set({ ...attr });
  }

  saveAttribute(): void {
    const attr = this.editAttribute();
    if (!attr.label.trim()) return;
    this.data.update(d => {
      const exists = d.voiceAttributes.find(a => a.id === attr.id);
      const voiceAttributes = exists
        ? d.voiceAttributes.map(a => a.id === attr.id ? { ...attr } : a)
        : [...d.voiceAttributes, { ...attr }];
      return { ...d, voiceAttributes };
    });
    this.editingAttributeId.set(null);
  }

  cancelEditAttribute(): void {
    this.editingAttributeId.set(null);
  }

  removeAttribute(id: string): void {
    this.data.update(d => ({
      ...d,
      voiceAttributes: d.voiceAttributes.filter(a => a.id !== id),
    }));
  }

  // --- Tone by Context ---

  startAddTone(): void {
    const newId = `tc-${Date.now()}`;
    this.editingToneId.set(newId);
    this.editTone.set({ id: newId, context: '', tone: '', example: '' });
  }

  startEditTone(tone: ToneContext): void {
    this.editingToneId.set(tone.id);
    this.editTone.set({ ...tone });
  }

  saveTone(): void {
    const tone = this.editTone();
    if (!tone.context.trim()) return;
    this.data.update(d => {
      const exists = d.toneByContext.find(t => t.id === tone.id);
      const toneByContext = exists
        ? d.toneByContext.map(t => t.id === tone.id ? { ...tone } : t)
        : [...d.toneByContext, { ...tone }];
      return { ...d, toneByContext };
    });
    this.editingToneId.set(null);
  }

  cancelEditTone(): void {
    this.editingToneId.set(null);
  }

  updateEditAttributeField(field: keyof VoiceAttribute, value: string): void {
    this.editAttribute.update(a => ({ ...a, [field]: value }));
  }

  updateEditToneField(field: keyof ToneContext, value: string): void {
    this.editTone.update(t => ({ ...t, [field]: value }));
  }

  removeTone(id: string): void {
    this.data.update(d => ({
      ...d,
      toneByContext: d.toneByContext.filter(t => t.id !== id),
    }));
  }

  generateToneContexts(): void {
    this.data.update(d => ({ ...d, toneByContext: MOCK_TONE_CONTEXTS }));
  }

  // --- Platform Tone Adjustments ---

  updatePlatformAdjustment(platform: Platform, value: string): void {
    this.data.update(d => ({
      ...d,
      platformToneAdjustments: d.platformToneAdjustments.map(p =>
        p.platform === platform ? { ...p, adjustment: value } : p
      ),
    }));
  }

  suggestPlatformTone(platform: Platform): void {
    this.suggestingPlatform.set(platform);
    setTimeout(() => {
      const suggestion = MOCK_PLATFORM_SUGGESTIONS[platform] ?? '';
      this.updatePlatformAdjustment(platform, suggestion);
      this.suggestingPlatform.set(null);
    }, 1500);
  }

  // --- Vocabulary ---

  addPreferredWord(): void {
    const word = this.newPreferredWord().trim();
    if (!word) return;
    this.data.update(d => ({
      ...d,
      vocabulary: { ...d.vocabulary, preferred: [...d.vocabulary.preferred, word] },
    }));
    this.newPreferredWord.set('');
  }

  removePreferredWord(word: string): void {
    this.data.update(d => ({
      ...d,
      vocabulary: { ...d.vocabulary, preferred: d.vocabulary.preferred.filter(w => w !== word) },
    }));
  }

  addAvoidWord(): void {
    const word = this.newAvoidWord().trim();
    if (!word) return;
    this.data.update(d => ({
      ...d,
      vocabulary: { ...d.vocabulary, avoid: [...d.vocabulary.avoid, word] },
    }));
    this.newAvoidWord.set('');
  }

  removeAvoidWord(word: string): void {
    this.data.update(d => ({
      ...d,
      vocabulary: { ...d.vocabulary, avoid: d.vocabulary.avoid.filter(w => w !== word) },
    }));
  }

  generateVocabulary(): void {
    this.data.update(d => ({
      ...d,
      vocabulary: {
        preferred: [...new Set([...d.vocabulary.preferred, ...MOCK_VOCAB.preferred])],
        avoid: [...new Set([...d.vocabulary.avoid, ...MOCK_VOCAB.avoid])],
      },
    }));
  }
}

<div class="brand-voice">
  <!-- Section 1: Mission Statement -->
  <section class="card">
    <div class="card-header">
      <svg class="card-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
        <circle cx="12" cy="12" r="10"/>
        <path d="m16 12-4-4-4 4M12 16V8"/>
      </svg>
      <h3 class="card-title">Mission Statement</h3>
    </div>
    <p class="card-description">Define the core purpose and promise of your brand voice.</p>
    <textarea
      class="mission-textarea"
      placeholder="Enter your brand's mission statement..."
      [ngModel]="data().missionStatement"
      (ngModelChange)="updateMission($event)"
      rows="4"
    ></textarea>
    <div class="card-actions">
      <button
        class="btn btn-ai"
        (click)="draftMission()"
        [disabled]="isDraftingMission()"
      >
        @if (!isDraftingMission()) {
          <svg class="btn-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
            <path d="M9.937 15.5A2 2 0 0 0 8.5 14.063l-6.135-1.582a.5.5 0 0 1 0-.962L8.5 9.936A2 2 0 0 0 9.937 8.5l1.582-6.135a.5.5 0 0 1 .963 0L14.063 8.5A2 2 0 0 0 15.5 9.937l6.135 1.581a.5.5 0 0 1 0 .964L15.5 14.063a2 2 0 0 0-1.437 1.437l-1.582 6.135a.5.5 0 0 1-.963 0z"/>
          </svg>
        }
        @if (isDraftingMission()) {
          <span class="spinner"></span>
        }
        {{ isDraftingMission() ? 'Drafting...' : 'AI Draft' }}
      </button>
    </div>
  </section>

  <!-- Section 2: Voice Attributes -->
  <section class="card">
    <div class="card-header">
      <svg class="card-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
        <path d="M12 2a3 3 0 0 0-3 3v7a3 3 0 0 0 6 0V5a3 3 0 0 0-3-3Z"/>
        <path d="M19 10v2a7 7 0 0 1-14 0v-2"/>
        <line x1="12" y1="19" x2="12" y2="22"/>
      </svg>
      <h3 class="card-title">Voice Attributes</h3>
    </div>
    <p class="card-description">Define key traits that characterize your brand voice, with do and don't examples.</p>

    <div class="attributes-grid">
      @for (attr of data().voiceAttributes; track attr.id) {
        <div class="attribute-card">
          <div class="attribute-header">
            <span class="attribute-label">{{ attr.label }}</span>
            <div class="attribute-actions">
              <button class="btn-icon-only" (click)="startEditAttribute(attr)" title="Edit">
                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M17 3a2.85 2.83 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5Z"/></svg>
              </button>
              <button class="btn-icon-only btn-danger" (click)="removeAttribute(attr.id)" title="Remove">
                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M3 6h18M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2"/></svg>
              </button>
            </div>
          </div>
          <p class="attribute-description">{{ attr.description }}</p>
          <div class="example-row do">
            <span class="example-badge do-badge">Do</span>
            <span class="example-text">{{ attr.doExample }}</span>
          </div>
          <div class="example-row dont">
            <span class="example-badge dont-badge">Don't</span>
            <span class="example-text">{{ attr.dontExample }}</span>
          </div>
        </div>
      }
    </div>

    <!-- Attribute edit form -->
    @if (editingAttributeId()) {
      <div class="inline-form">
        <div class="form-row">
          <input
            class="form-input"
            placeholder="Attribute label"
            [ngModel]="editAttribute().label"
            (ngModelChange)="updateEditAttributeField('label', $event)"
          />
        </div>
        <div class="form-row">
          <input
            class="form-input"
            placeholder="Description"
            [ngModel]="editAttribute().description"
            (ngModelChange)="updateEditAttributeField('description', $event)"
          />
        </div>
        <div class="form-row">
          <input
            class="form-input"
            placeholder="Do example"
            [ngModel]="editAttribute().doExample"
            (ngModelChange)="updateEditAttributeField('doExample', $event)"
          />
        </div>
        <div class="form-row">
          <input
            class="form-input"
            placeholder="Don't example"
            [ngModel]="editAttribute().dontExample"
            (ngModelChange)="updateEditAttributeField('dontExample', $event)"
          />
        </div>
        <div class="form-actions">
          <button class="btn btn-primary" (click)="saveAttribute()">Save</button>
          <button class="btn btn-secondary" (click)="cancelEditAttribute()">Cancel</button>
        </div>
      </div>
    }

    <div class="card-actions">
      <button class="btn btn-secondary" (click)="startAddAttribute()">
        <svg class="btn-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="12" y1="5" x2="12" y2="19"/><line x1="5" y1="12" x2="19" y2="12"/></svg>
        Add Attribute
      </button>
      <button
        class="btn btn-ai"
        (click)="generateAttributes()"
        [disabled]="isGeneratingAttributes()"
      >
        @if (!isGeneratingAttributes()) {
          <svg class="btn-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
            <path d="M9.937 15.5A2 2 0 0 0 8.5 14.063l-6.135-1.582a.5.5 0 0 1 0-.962L8.5 9.936A2 2 0 0 0 9.937 8.5l1.582-6.135a.5.5 0 0 1 .963 0L14.063 8.5A2 2 0 0 0 15.5 9.937l6.135 1.581a.5.5 0 0 1 0 .964L15.5 14.063a2 2 0 0 0-1.437 1.437l-1.582 6.135a.5.5 0 0 1-.963 0z"/>
          </svg>
        }
        @if (isGeneratingAttributes()) {
          <span class="spinner"></span>
        }
        {{ isGeneratingAttributes() ? 'Generating...' : 'AI Generate' }}
      </button>
    </div>
  </section>

  <!-- Section 3: Tone by Context -->
  <section class="card">
    <div class="card-header">
      <svg class="card-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
        <path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"/>
      </svg>
      <h3 class="card-title">Tone by Context</h3>
    </div>
    <p class="card-description">Map how your tone shifts across different content contexts.</p>

    @if (data().toneByContext.length > 0) {
      <div class="tone-table-wrapper">
        <table class="tone-table">
          <thead>
            <tr>
              <th>Context</th>
              <th>Tone</th>
              <th>Example</th>
              <th class="actions-col">Actions</th>
            </tr>
          </thead>
          <tbody>
            @for (tone of data().toneByContext; track tone.id) {
              <tr>
                <td class="context-cell">{{ tone.context }}</td>
                <td>{{ tone.tone }}</td>
                <td class="example-cell">{{ tone.example }}</td>
                <td class="actions-col">
                  <button class="btn-icon-only" (click)="startEditTone(tone)" title="Edit">
                    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M17 3a2.85 2.83 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5Z"/></svg>
                  </button>
                  <button class="btn-icon-only btn-danger" (click)="removeTone(tone.id)" title="Remove">
                    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M3 6h18M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2"/></svg>
                  </button>
                </td>
              </tr>
            }
          </tbody>
        </table>
      </div>
    }

    @if (data().toneByContext.length === 0) {
      <p class="empty-state">No tone contexts yet. Add one or generate with AI.</p>
    }

    <!-- Tone edit form -->
    @if (editingToneId()) {
      <div class="inline-form">
        <div class="form-row">
          <input
            class="form-input"
            placeholder="Context (e.g. Educational)"
            [ngModel]="editTone().context"
            (ngModelChange)="updateEditToneField('context', $event)"
          />
        </div>
        <div class="form-row">
          <input
            class="form-input"
            placeholder="Tone description"
            [ngModel]="editTone().tone"
            (ngModelChange)="updateEditToneField('tone', $event)"
          />
        </div>
        <div class="form-row">
          <input
            class="form-input"
            placeholder="Example sentence"
            [ngModel]="editTone().example"
            (ngModelChange)="updateEditToneField('example', $event)"
          />
        </div>
        <div class="form-actions">
          <button class="btn btn-primary" (click)="saveTone()">Save</button>
          <button class="btn btn-secondary" (click)="cancelEditTone()">Cancel</button>
        </div>
      </div>
    }

    <div class="card-actions">
      <button class="btn btn-secondary" (click)="startAddTone()">
        <svg class="btn-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="12" y1="5" x2="12" y2="19"/><line x1="5" y1="12" x2="19" y2="12"/></svg>
        Add Context
      </button>
    </div>
  </section>

  <!-- Section 4: Platform Tone Adjustments -->
  <section class="card">
    <div class="card-header">
      <svg class="card-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
        <path d="M4.9 19.1C1 15.2 1 8.8 4.9 4.9"/>
        <path d="M7.8 16.2a5 5 0 0 1 0-8.4"/>
        <path d="M16.2 7.8a5 5 0 0 1 0 8.4"/>
        <path d="M19.1 4.9C23 8.8 23 15.1 19.1 19"/>
        <circle cx="12" cy="12" r="1"/>
      </svg>
      <h3 class="card-title">Platform Tone Adjustments</h3>
    </div>
    <p class="card-description">Tailor your tone for each platform's unique audience and format.</p>

    <div class="platform-grid">
      @for (entry of data().platformToneAdjustments; track entry.platform) {
        <div class="platform-card">
          <div class="platform-header">
            <span class="platform-label">{{ platformLabels[entry.platform] }}</span>
            <button
              class="btn btn-ai btn-sm"
              (click)="suggestPlatformTone(entry.platform)"
              [disabled]="suggestingPlatform() === entry.platform"
            >
              @if (suggestingPlatform() === entry.platform) {
                <span class="spinner"></span>
              }
              {{ suggestingPlatform() === entry.platform ? 'Suggesting...' : 'AI Suggest' }}
            </button>
          </div>
          <textarea
            class="platform-textarea"
            [placeholder]="'How should the tone adapt for ' + platformLabels[entry.platform] + '?'"
            [ngModel]="entry.adjustment"
            (ngModelChange)="updatePlatformAdjustment(entry.platform, $event)"
            rows="3"
          ></textarea>
        </div>
      }
    </div>
  </section>

  <!-- Section 5: Vocabulary Guide -->
  <section class="card">
    <div class="card-header">
      <svg class="card-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
        <path d="M2 3h6a4 4 0 0 1 4 4v14a3 3 0 0 0-3-3H2z"/>
        <path d="M22 3h-6a4 4 0 0 0-4 4v14a3 3 0 0 1 3-3h7z"/>
      </svg>
      <h3 class="card-title">Vocabulary Guide</h3>
    </div>
    <p class="card-description">Curate preferred and avoided terms to keep messaging consistent.</p>

    <div class="vocab-columns">
      <div class="vocab-column preferred-column">
        <h4 class="vocab-heading preferred-heading">Preferred Terms</h4>
        <div class="chip-list">
          @for (word of data().vocabulary.preferred; track word) {
            <span class="chip chip-preferred">
              {{ word }}
              <button class="chip-remove" (click)="removePreferredWord(word)" title="Remove">&times;</button>
            </span>
          }
        </div>
        <div class="vocab-input-row">
          <input
            class="form-input"
            placeholder="Add preferred term..."
            [ngModel]="newPreferredWord()"
            (ngModelChange)="newPreferredWord.set($event)"
            (keyup.enter)="addPreferredWord()"
          />
          <button class="btn btn-secondary btn-sm" (click)="addPreferredWord()">Add</button>
        </div>
      </div>

      <div class="vocab-column avoid-column">
        <h4 class="vocab-heading avoid-heading">Terms to Avoid</h4>
        <div class="chip-list">
          @for (word of data().vocabulary.avoid; track word) {
            <span class="chip chip-avoid">
              {{ word }}
              <button class="chip-remove" (click)="removeAvoidWord(word)" title="Remove">&times;</button>
            </span>
          }
        </div>
        <div class="vocab-input-row">
          <input
            class="form-input"
            placeholder="Add term to avoid..."
            [ngModel]="newAvoidWord()"
            (ngModelChange)="newAvoidWord.set($event)"
            (keyup.enter)="addAvoidWord()"
          />
          <button class="btn btn-secondary btn-sm" (click)="addAvoidWord()">Add</button>
        </div>
      </div>
    </div>

    <div class="card-actions">
      <button class="btn btn-ai" (click)="generateVocabulary()">
        <svg class="btn-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
          <path d="M9.937 15.5A2 2 0 0 0 8.5 14.063l-6.135-1.582a.5.5 0 0 1 0-.962L8.5 9.936A2 2 0 0 0 9.937 8.5l1.582-6.135a.5.5 0 0 1 .963 0L14.063 8.5A2 2 0 0 0 15.5 9.937l6.135 1.581a.5.5 0 0 1 0 .964L15.5 14.063a2 2 0 0 0-1.437 1.437l-1.582 6.135a.5.5 0 0 1-.963 0z"/>
        </svg>
        AI Generate Vocabulary
      </button>
    </div>
  </section>
</div>

// figma/src/app/components/content/BrandVoice.tsx
import React, { useState } from "react";
import {
  Mic,
  Plus,
  Trash2,
  Edit3,
  Check,
  X,
  Loader2,
  Sparkles,
  ChevronDown,
} from "lucide-react";
import { Button } from "@/app/components/ui/button";
import { Input } from "@/app/components/ui/input";
import { Textarea } from "@/app/components/ui/textarea";
import { Card, CardContent } from "@/app/components/ui/card";
import { Badge } from "@/app/components/ui/badge";
import { Label } from "@/app/components/ui/label";
import type { BrandVoice, VoiceAttribute, ToneContext } from "./types";
import { PLATFORM_CONFIG } from "./types";
import { cn } from "@/lib/utils";
import { toast } from "sonner";

interface BrandVoiceProps {
  brandVoice: BrandVoice;
  onUpdateBrandVoice: (bv: BrandVoice) => void;
}

const MOCK_VOICE_ATTRIBUTES: VoiceAttribute[] = [
  {
    id: "va1",
    label: "Empowering",
    description: "We lift women up, never talk down to them.",
    doExample: "You have everything it takes — let's unlock it together.",
    dontExample: "You need to fix your relationship with your body.",
  },
  {
    id: "va2",
    label: "Knowledgeable but Accessible",
    description: "Expert-backed but never jargon-heavy.",
    doExample: "Estrogen affects your muscle recovery — here's what that means for your workouts.",
    dontExample: "HRT-mediated myofibrillar protein synthesis rates indicate...",
  },
  {
    id: "va3",
    label: "Warm & Inclusive",
    description: "Every woman in her 40s belongs here.",
    doExample: "Whether you're a lifelong athlete or just rediscovering movement — this is your space.",
    dontExample: "For women who are already committed to fitness.",
  },
  {
    id: "va4",
    label: "Honest & Real",
    description: "No toxic positivity, no impossible standards.",
    doExample: "Some days perimenopause wins. That's real. Here's how to adapt.",
    dontExample: "Every day is an opportunity to crush it!",
  },
];

const MOCK_TONE_CONTEXTS: ToneContext[] = [
  { id: "tc1", context: "Educational", tone: "Clear, authoritative, relatable — translate science into actionable insight", example: "Here's what's actually happening in your body during perimenopause — and what you can do about it today." },
  { id: "tc2", context: "Motivational", tone: "Energetic, affirming, forward-looking", example: "Your strongest decade might just be the one you're stepping into right now." },
  { id: "tc3", context: "Community", tone: "Warm, conversational, curious — invite participation", example: "What's been your biggest shift in how you train since turning 40? Drop it below 👇" },
  { id: "tc4", context: "Promotional", tone: "Honest and benefit-led — never pushy", example: "We built this program for the woman who knows what she wants but needs the right tools." },
];

const MOCK_VOCAB = {
  preferred: ["perimenopause", "hormonal shift", "movement", "reclaim", "adapt", "community", "evidence-backed", "sustainable"],
  avoid: ["anti-aging", "fight", "battle", "fix your body", "before & after", "dramatic results"],
};

const MOCK_PLATFORM_SUGGESTIONS: Record<string, string> = {
  instagram: "Warm, visual storytelling. Use emojis sparingly. Captions can be medium-length with a strong hook.",
  tiktok: "Fast-paced and conversational — mirror trending audio language. Hook within 2 seconds. Short punchy sentences.",
  youtube: "Thorough and evidence-backed. Viewers opt in for depth — reward them with real value. Earn trust over time.",
  facebook: "Community-first. Ask questions, celebrate wins, invite discussion. More personal and conversational.",
  linkedin: "Professional but human — share expertise with personal context. Longer-form insights welcome.",
};

const ACTIVE_PLATFORMS = ["instagram", "tiktok", "youtube", "facebook", "linkedin"] as const;

const EMPTY_ATTR_FORM = { label: "", description: "", doExample: "", dontExample: "" };
const EMPTY_TONE_FORM = { context: "", tone: "", example: "" };

export function BrandVoice({ brandVoice, onUpdateBrandVoice }: BrandVoiceProps) {
  // Section 1 — Mission
  const [mission, setMission] = useState(brandVoice.missionStatement);
  const [isDraftingMission, setIsDraftingMission] = useState(false);

  // Section 2 — Voice Attributes
  const [showAttrForm, setShowAttrForm] = useState(false);
  const [attrForm, setAttrForm] = useState(EMPTY_ATTR_FORM);
  const [editingAttrId, setEditingAttrId] = useState<string | null>(null);
  const [isGeneratingAttrs, setIsGeneratingAttrs] = useState(false);

  // Section 3 — Tone by Context
  const [showToneForm, setShowToneForm] = useState(false);
  const [toneForm, setToneForm] = useState(EMPTY_TONE_FORM);
  const [editingToneId, setEditingToneId] = useState<string | null>(null);

  // Section 4 — Platform adjustments
  const [platformSuggestingId, setPlatformSuggestingId] = useState<string | null>(null);

  // Section 5 — Vocabulary
  const [preferredInput, setPreferredInput] = useState("");
  const [avoidInput, setAvoidInput] = useState("");
  const [isGeneratingVocab, setIsGeneratingVocab] = useState(false);

  const update = (updates: Partial<BrandVoice>) => {
    onUpdateBrandVoice({ ...brandVoice, ...updates });
  };

  // Mission
  const handleSaveMission = () => {
    update({ missionStatement: mission });
    toast.success("Mission statement saved");
  };

  const handleDraftMission = () => {
    setIsDraftingMission(true);
    setTimeout(() => {
      const drafted = "We create content to help women in their 40s and 50s reclaim their strength and vitality during perimenopause by providing evidence-backed movement guidance and a supportive community that meets them where they are.";
      setMission(drafted);
      update({ missionStatement: drafted });
      setIsDraftingMission(false);
      toast.success("Mission drafted");
    }, 2500);
  };

  // Voice Attributes
  const handleSaveAttr = () => {
    if (!attrForm.label.trim()) return;
    if (editingAttrId) {
      update({
        voiceAttributes: brandVoice.voiceAttributes.map((a) =>
          a.id === editingAttrId ? { ...a, ...attrForm } : a
        ),
      });
    } else {
      const newAttr: VoiceAttribute = { id: `va-${Date.now()}`, ...attrForm };
      update({ voiceAttributes: [...brandVoice.voiceAttributes, newAttr] });
    }
    setAttrForm(EMPTY_ATTR_FORM);
    setShowAttrForm(false);
    setEditingAttrId(null);
    toast.success(editingAttrId ? "Attribute updated" : "Attribute added");
  };

  const handleEditAttr = (attr: VoiceAttribute) => {
    setEditingAttrId(attr.id);
    setAttrForm({ label: attr.label, description: attr.description, doExample: attr.doExample, dontExample: attr.dontExample });
    setShowAttrForm(true);
  };

  const handleDeleteAttr = (id: string) => {
    update({ voiceAttributes: brandVoice.voiceAttributes.filter((a) => a.id !== id) });
  };

  const handleGenerateAttrs = () => {
    setIsGeneratingAttrs(true);
    setTimeout(() => {
      update({ voiceAttributes: MOCK_VOICE_ATTRIBUTES });
      setIsGeneratingAttrs(false);
      toast.success("Voice attributes generated");
    }, 2500);
  };

  // Tone by Context
  const handleSaveTone = () => {
    if (!toneForm.context.trim()) return;
    if (editingToneId) {
      update({
        toneByContext: brandVoice.toneByContext.map((t) =>
          t.id === editingToneId ? { ...t, ...toneForm } : t
        ),
      });
    } else {
      const newTone: ToneContext = { id: `tc-${Date.now()}`, ...toneForm };
      update({ toneByContext: [...brandVoice.toneByContext, newTone] });
    }
    setToneForm(EMPTY_TONE_FORM);
    setShowToneForm(false);
    setEditingToneId(null);
  };

  const handleEditTone = (tc: ToneContext) => {
    setEditingToneId(tc.id);
    setToneForm({ context: tc.context, tone: tc.tone, example: tc.example });
    setShowToneForm(true);
  };

  const handleDeleteTone = (id: string) => {
    update({ toneByContext: brandVoice.toneByContext.filter((t) => t.id !== id) });
  };

  const handleGenerateTone = () => {
    update({ toneByContext: MOCK_TONE_CONTEXTS });
    toast.success("Tone contexts generated");
  };

  // Platform Tone
  const handlePlatformAdjustmentChange = (platform: string, value: string) => {
    const updated = brandVoice.platformToneAdjustments.map((p) =>
      p.platform === platform ? { ...p, adjustment: value } : p
    );
    update({ platformToneAdjustments: updated });
  };

  const handleAISuggestPlatform = (platform: string) => {
    setPlatformSuggestingId(platform);
    setTimeout(() => {
      const suggestion = MOCK_PLATFORM_SUGGESTIONS[platform] || "";
      const updated = brandVoice.platformToneAdjustments.map((p) =>
        p.platform === platform ? { ...p, adjustment: suggestion } : p
      );
      update({ platformToneAdjustments: updated });
      setPlatformSuggestingId(null);
      toast.success(`Tone suggestion added for ${PLATFORM_CONFIG[platform as keyof typeof PLATFORM_CONFIG]?.label ?? platform}`);
    }, 1500);
  };

  // Vocabulary
  const addPreferred = () => {
    const word = preferredInput.trim();
    if (!word || brandVoice.vocabulary.preferred.includes(word)) return;
    update({ vocabulary: { ...brandVoice.vocabulary, preferred: [...brandVoice.vocabulary.preferred, word] } });
    setPreferredInput("");
  };

  const addAvoid = () => {
    const word = avoidInput.trim();
    if (!word || brandVoice.vocabulary.avoid.includes(word)) return;
    update({ vocabulary: { ...brandVoice.vocabulary, avoid: [...brandVoice.vocabulary.avoid, word] } });
    setAvoidInput("");
  };

  const removePreferred = (word: string) => {
    update({ vocabulary: { ...brandVoice.vocabulary, preferred: brandVoice.vocabulary.preferred.filter((w) => w !== word) } });
  };

  const removeAvoid = (word: string) => {
    update({ vocabulary: { ...brandVoice.vocabulary, avoid: brandVoice.vocabulary.avoid.filter((w) => w !== word) } });
  };

  const handleGenerateVocab = () => {
    setIsGeneratingVocab(true);
    setTimeout(() => {
      update({ vocabulary: MOCK_VOCAB });
      setIsGeneratingVocab(false);
      toast.success("Vocabulary guide generated");
    }, 2500);
  };

  return (
    <div className="space-y-8">
      {/* Header */}
      <div className="flex items-center gap-2">
        <div className="p-2 rounded-lg bg-[#d94e33]/10">
          <Mic className="size-4 text-[#d94e33]" />
        </div>
        <div>
          <h3 className="font-bold text-gray-900">Brand Voice & Tone</h3>
          <p className="text-xs text-muted-foreground">Define how your brand speaks, sounds, and connects with your audience</p>
        </div>
      </div>

      {/* ── Section 1: Content Mission ── */}
      <div>
        <div className="flex items-center justify-between mb-3">
          <div>
            <p className="text-xs font-bold uppercase tracking-wider text-muted-foreground">Content Mission Statement</p>
            <p className="text-xs text-muted-foreground mt-0.5">Complete this sentence: We create content to help [audience] [achieve outcome] by [our approach].</p>
          </div>
          <Button
            size="sm"
            variant="outline"
            className="gap-1.5 h-8 text-xs shrink-0"
            onClick={handleDraftMission}
            disabled={isDraftingMission}
          >
            {isDraftingMission ? <Loader2 className="size-3 animate-spin" /> : <Sparkles className="size-3 text-[#d94e33]" />}
            Draft Mission
          </Button>
        </div>
        <Textarea
          value={mission}
          onChange={(e) => setMission(e.target.value)}
          placeholder="We create content to help women in their 40s reclaim their energy and strength during perimenopause by..."
          className="min-h-[100px] resize-none text-sm"
        />
        <div className="flex justify-end mt-2">
          <Button size="sm" className="bg-[#d94e33] hover:bg-[#c4452d] h-8 text-xs" onClick={handleSaveMission}>
            <Check className="size-3 mr-1" /> Save Mission
          </Button>
        </div>
      </div>

      {/* ── Section 2: Voice Attributes ── */}
      <div>
        <div className="flex items-center justify-between mb-3">
          <div>
            <p className="text-xs font-bold uppercase tracking-wider text-muted-foreground">Brand Personality</p>
            <p className="text-xs text-muted-foreground mt-0.5">3–5 defining traits that shape how your brand communicates</p>
          </div>
          <div className="flex items-center gap-2">
            <Button
              size="sm"
              variant="outline"
              className="gap-1.5 h-8 text-xs"
              onClick={handleGenerateAttrs}
              disabled={isGeneratingAttrs}
            >
              {isGeneratingAttrs ? <Loader2 className="size-3 animate-spin" /> : <Sparkles className="size-3 text-[#d94e33]" />}
              AI Generate
            </Button>
            <Button
              size="sm"
              className="bg-[#d94e33] hover:bg-[#c4452d] h-8 gap-1 text-xs"
              onClick={() => { setShowAttrForm(true); setEditingAttrId(null); setAttrForm(EMPTY_ATTR_FORM); }}
            >
              <Plus className="size-3" /> Add Attribute
            </Button>
          </div>
        </div>

        {/* Attribute form */}
        {showAttrForm && (
          <Card className="border-dashed border-[#d94e33]/40 mb-4">
            <CardContent className="p-4 space-y-3">
              <p className="text-xs font-bold uppercase tracking-wider text-muted-foreground">{editingAttrId ? "Edit" : "New"} Voice Attribute</p>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                <div>
                  <Label className="text-xs text-muted-foreground">Label</Label>
                  <Input value={attrForm.label} onChange={(e) => setAttrForm({ ...attrForm, label: e.target.value })} placeholder="e.g. Empowering" className="mt-1 h-8 text-sm" />
                </div>
                <div>
                  <Label className="text-xs text-muted-foreground">Description</Label>
                  <Input value={attrForm.description} onChange={(e) => setAttrForm({ ...attrForm, description: e.target.value })} placeholder="What this means for the brand" className="mt-1 h-8 text-sm" />
                </div>
                <div>
                  <Label className="text-xs text-muted-foreground">Do Example</Label>
                  <Input value={attrForm.doExample} onChange={(e) => setAttrForm({ ...attrForm, doExample: e.target.value })} placeholder="Example done right" className="mt-1 h-8 text-sm" />
                </div>
                <div>
                  <Label className="text-xs text-muted-foreground">Don't Example</Label>
                  <Input value={attrForm.dontExample} onChange={(e) => setAttrForm({ ...attrForm, dontExample: e.target.value })} placeholder="Example to avoid" className="mt-1 h-8 text-sm" />
                </div>
              </div>
              <div className="flex gap-2">
                <Button size="sm" className="bg-[#d94e33] hover:bg-[#c4452d] h-8 text-xs" onClick={handleSaveAttr}>Save</Button>
                <Button size="sm" variant="outline" className="h-8 text-xs" onClick={() => { setShowAttrForm(false); setEditingAttrId(null); }}>Cancel</Button>
              </div>
            </CardContent>
          </Card>
        )}

        {brandVoice.voiceAttributes.length === 0 && !showAttrForm && (
          <div className="rounded-lg border border-dashed border-gray-200 p-6 text-center">
            <Mic className="size-6 text-gray-300 mx-auto mb-2" />
            <p className="text-sm text-muted-foreground">No voice attributes defined yet. Add attributes or use AI Generate.</p>
          </div>
        )}

        <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
          {brandVoice.voiceAttributes.map((attr) => (
            <Card key={attr.id} className="border-gray-100 group hover:border-gray-200 transition-colors">
              <CardContent className="p-4">
                <div className="flex items-start justify-between mb-2">
                  <span className="font-bold text-sm text-gray-900">{attr.label}</span>
                  <div className="flex items-center gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
                    <button onClick={() => handleEditAttr(attr)} className="p-1 rounded hover:bg-gray-100 text-muted-foreground hover:text-[#d94e33]">
                      <Edit3 className="size-3" />
                    </button>
                    <button onClick={() => handleDeleteAttr(attr.id)} className="p-1 rounded hover:bg-gray-100 text-muted-foreground hover:text-destructive">
                      <Trash2 className="size-3" />
                    </button>
                  </div>
                </div>
                <p className="text-xs text-muted-foreground mb-3">{attr.description}</p>
                <div className="space-y-1.5">
                  <div className="rounded-md bg-green-50 border border-green-100 px-3 py-1.5">
                    <p className="text-[10px] font-bold uppercase tracking-wider text-green-700 mb-0.5">Do</p>
                    <p className="text-xs text-green-800">"{attr.doExample}"</p>
                  </div>
                  <div className="rounded-md bg-red-50 border border-red-100 px-3 py-1.5">
                    <p className="text-[10px] font-bold uppercase tracking-wider text-red-700 mb-0.5">Don't</p>
                    <p className="text-xs text-red-800">"{attr.dontExample}"</p>
                  </div>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      </div>

      {/* ── Section 3: Tone by Context ── */}
      <div>
        <div className="flex items-center justify-between mb-3">
          <div>
            <p className="text-xs font-bold uppercase tracking-wider text-muted-foreground">Tone Shifts</p>
            <p className="text-xs text-muted-foreground mt-0.5">How your voice adapts in different content situations</p>
          </div>
          <div className="flex items-center gap-2">
            <Button size="sm" variant="outline" className="gap-1.5 h-8 text-xs" onClick={handleGenerateTone}>
              <Sparkles className="size-3 text-[#d94e33]" /> AI Generate
            </Button>
            <Button size="sm" className="bg-[#d94e33] hover:bg-[#c4452d] h-8 gap-1 text-xs" onClick={() => { setShowToneForm(true); setEditingToneId(null); setToneForm(EMPTY_TONE_FORM); }}>
              <Plus className="size-3" /> Add Context
            </Button>
          </div>
        </div>

        {showToneForm && (
          <Card className="border-dashed border-[#d94e33]/40 mb-4">
            <CardContent className="p-4 space-y-3">
              <p className="text-xs font-bold uppercase tracking-wider text-muted-foreground">{editingToneId ? "Edit" : "New"} Context</p>
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
                <div>
                  <Label className="text-xs text-muted-foreground">Context</Label>
                  <Input value={toneForm.context} onChange={(e) => setToneForm({ ...toneForm, context: e.target.value })} placeholder="e.g. Educational" className="mt-1 h-8 text-sm" />
                </div>
                <div>
                  <Label className="text-xs text-muted-foreground">Tone Description</Label>
                  <Input value={toneForm.tone} onChange={(e) => setToneForm({ ...toneForm, tone: e.target.value })} placeholder="How the voice sounds here" className="mt-1 h-8 text-sm" />
                </div>
                <div>
                  <Label className="text-xs text-muted-foreground">Example Line</Label>
                  <Input value={toneForm.example} onChange={(e) => setToneForm({ ...toneForm, example: e.target.value })} placeholder="Sample copy" className="mt-1 h-8 text-sm" />
                </div>
              </div>
              <div className="flex gap-2">
                <Button size="sm" className="bg-[#d94e33] hover:bg-[#c4452d] h-8 text-xs" onClick={handleSaveTone}>Save</Button>
                <Button size="sm" variant="outline" className="h-8 text-xs" onClick={() => { setShowToneForm(false); setEditingToneId(null); }}>Cancel</Button>
              </div>
            </CardContent>
          </Card>
        )}

        {brandVoice.toneByContext.length === 0 && !showToneForm ? (
          <div className="rounded-lg border border-dashed border-gray-200 p-6 text-center">
            <p className="text-sm text-muted-foreground">No tone contexts defined. Add contexts or use AI Generate.</p>
          </div>
        ) : (
          <div className="rounded-lg border border-gray-100 overflow-hidden">
            {/* Table header */}
            <div className="grid grid-cols-3 gap-3 px-4 py-2 bg-gray-50/70 border-b border-gray-100">
              <span className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">Context</span>
              <span className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">Tone</span>
              <span className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">Example</span>
            </div>
            <div className="divide-y divide-gray-50">
              {brandVoice.toneByContext.map((tc) => (
                <div key={tc.id} className="grid grid-cols-3 gap-3 px-4 py-3 group hover:bg-gray-50/50 transition-colors">
                  <div className="flex items-center gap-2">
                    <span className="text-sm font-bold text-gray-900">{tc.context}</span>
                    <div className="flex items-center gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
                      <button onClick={() => handleEditTone(tc)} className="p-1 rounded hover:bg-gray-100 text-muted-foreground hover:text-[#d94e33]">
                        <Edit3 className="size-3" />
                      </button>
                      <button onClick={() => handleDeleteTone(tc.id)} className="p-1 rounded hover:bg-gray-100 text-muted-foreground hover:text-destructive">
                        <Trash2 className="size-3" />
                      </button>
                    </div>
                  </div>
                  <p className="text-xs text-gray-700 self-center">{tc.tone}</p>
                  <p className="text-xs text-muted-foreground italic self-center">"{tc.example}"</p>
                </div>
              ))}
            </div>
          </div>
        )}
      </div>

      {/* ── Section 4: Platform Tone Adjustments ── */}
      <div>
        <div className="mb-3">
          <p className="text-xs font-bold uppercase tracking-wider text-muted-foreground">Platform Nuances</p>
          <p className="text-xs text-muted-foreground mt-0.5">How your voice shifts on each platform</p>
        </div>
        <div className="space-y-3">
          {brandVoice.platformToneAdjustments
            .filter((p) => ACTIVE_PLATFORMS.includes(p.platform as typeof ACTIVE_PLATFORMS[number]))
            .map((p) => {
              const cfg = PLATFORM_CONFIG[p.platform];
              return (
                <div key={p.platform} className="flex items-start gap-3">
                  <div className="w-24 shrink-0 pt-2">
                    <span className={cn("text-xs font-bold", cfg?.color)}>{cfg?.label ?? p.platform}</span>
                  </div>
                  <div className="flex-1">
                    <Input
                      value={p.adjustment}
                      onChange={(e) => handlePlatformAdjustmentChange(p.platform, e.target.value)}
                      placeholder={`Tone notes for ${cfg?.label ?? p.platform}...`}
                      className="h-9 text-sm"
                    />
                  </div>
                  <Button
                    size="sm"
                    variant="outline"
                    className="h-9 gap-1.5 text-xs shrink-0"
                    onClick={() => handleAISuggestPlatform(p.platform)}
                    disabled={platformSuggestingId === p.platform}
                  >
                    {platformSuggestingId === p.platform ? (
                      <Loader2 className="size-3 animate-spin" />
                    ) : (
                      <Sparkles className="size-3 text-[#d94e33]" />
                    )}
                    AI Suggest
                  </Button>
                </div>
              );
            })}
        </div>
      </div>

      {/* ── Section 5: Vocabulary Guide ── */}
      <div>
        <div className="flex items-center justify-between mb-3">
          <div>
            <p className="text-xs font-bold uppercase tracking-wider text-muted-foreground">Vocabulary Guide</p>
            <p className="text-xs text-muted-foreground mt-0.5">Words and phrases that define your brand's language</p>
          </div>
          <Button
            size="sm"
            variant="outline"
            className="gap-1.5 h-8 text-xs"
            onClick={handleGenerateVocab}
            disabled={isGeneratingVocab}
          >
            {isGeneratingVocab ? <Loader2 className="size-3 animate-spin" /> : <Sparkles className="size-3 text-[#d94e33]" />}
            AI Generate
          </Button>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {/* Use These Words */}
          <div className="rounded-lg border border-green-100 bg-green-50/30 p-4">
            <p className="text-xs font-bold text-green-700 mb-3">Use These Words</p>
            <div className="flex flex-wrap gap-1.5 mb-3 min-h-[32px]">
              {brandVoice.vocabulary.preferred.map((word) => (
                <Badge key={word} variant="outline" className="bg-green-50 text-green-700 border-green-200 gap-1 pr-1">
                  {word}
                  <button onClick={() => removePreferred(word)} className="hover:text-destructive ml-0.5">
                    <X className="size-2.5" />
                  </button>
                </Badge>
              ))}
            </div>
            <div className="flex gap-2">
              <Input
                value={preferredInput}
                onChange={(e) => setPreferredInput(e.target.value)}
                onKeyDown={(e) => e.key === "Enter" && addPreferred()}
                placeholder="Add word or phrase..."
                className="h-8 text-xs"
              />
              <Button size="sm" className="h-8 bg-[#d94e33] hover:bg-[#c4452d] text-xs" onClick={addPreferred}>Add</Button>
            </div>
          </div>

          {/* Avoid These Words */}
          <div className="rounded-lg border border-red-100 bg-red-50/30 p-4">
            <p className="text-xs font-bold text-red-700 mb-3">Avoid These Words</p>
            <div className="flex flex-wrap gap-1.5 mb-3 min-h-[32px]">
              {brandVoice.vocabulary.avoid.map((word) => (
                <Badge key={word} variant="outline" className="bg-red-50 text-red-700 border-red-200 gap-1 pr-1">
                  {word}
                  <button onClick={() => removeAvoid(word)} className="hover:text-destructive ml-0.5">
                    <X className="size-2.5" />
                  </button>
                </Badge>
              ))}
            </div>
            <div className="flex gap-2">
              <Input
                value={avoidInput}
                onChange={(e) => setAvoidInput(e.target.value)}
                onKeyDown={(e) => e.key === "Enter" && addAvoid()}
                placeholder="Add word or phrase..."
                className="h-8 text-xs"
              />
              <Button size="sm" className="h-8 bg-[#d94e33] hover:bg-[#c4452d] text-xs" onClick={addAvoid}>Add</Button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
